# Generated by Django 5.0.4 on 2024-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='მოდელი')),
                ('first_preis', models.IntegerField(verbose_name='ფასი 3 საათით')),
                ('second_preis', models.IntegerField(verbose_name='ფასი 24 საათით')),
                ('purpose', models.CharField(max_length=20, verbose_name='დანიშნულება')),
            ],
        ),
    ]
