# Generated by Django 5.0.4 on 2024-04-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_images/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.student')),
            ],
        ),
    ]
