# Generated by Django 5.0.4 on 2024-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='purpose',
            field=models.CharField(max_length=400, verbose_name='დანიშნულება'),
        ),
    ]
