# Generated by Django 5.0.4 on 2024-05-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_purpose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Device',
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='device_images/')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.device')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentImage',
        ),
    ]
