# Generated by Django 5.0.4 on 2024-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_student_device_deviceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='first_preis',
            field=models.CharField(max_length=100, verbose_name='საათიების რაოდენობა და ფასი'),
        ),
        migrations.AlterField(
            model_name='device',
            name='second_preis',
            field=models.CharField(max_length=100, verbose_name='საათიების რაოდენობა და ფასი'),
        ),
    ]
